src/app/page.tsx

[민우] - 배포용 초기 페이지 설정 

---

next.config.js
src/styles/origin-theme.scss
src/styles/standard.scss
src/styles/variables.scss

close #6 
- font, border global variables 추가
- color, shadow variables 추가
- scss 파일 절대경로로 @import 하기 위해 next.config.js 설정 추가

[혜수] - 메인 색상, 폰트 크기, border-radius, 그림자 추가

---

.github/workflows/close-issue.yml

close #18 
- github action 추가
- ACTION_TOKEN 설정 추가

[혜수] - dev branch에 merge시 연결된 issue 자동 close

---

.gitignore
src/app/layout.tsx
src/styles/class/background.scss
src/styles/class/color.scss
src/styles/class/font-size.scss
src/styles/class/mixin.scss
src/styles/origin-theme.scss
src/styles/standard.scss
src/styles/variables.scss

[혜수] - 공통 scss 배경색, 폰트색, 폰트 크기 추가

---

src/styles/standard.scss

close #20 
- border-radious -> border-radius로 수정했습니다.

[혜수] - border-radious -> border-radius로 수정

---

src/components/AjajaButton/AjajaButton.tsx
src/components/AjajaButton/index.scss
src/components/index.ts

close #9 
- 일단 `아좌좌`는 `0.375rem`인데 여기서만 쓰는 것 같아 인라인 style 적용했습니다. 더 사용하는 곳이 있다면 전역으로 빼겠습니다. 
- 사용법
```tsx
interface AjajaButtonProps {
isFilled: boolean;
onClick: () => void;
children: React.ReactNode;
}
```
```tsx
'use client';
import { AjajaButton } from '@/components';
import { useState } from 'react';
const [click, setClick] = useState(false);
const [number, setNumber] = useState(0);
const handleClick = () => {
if (!click) setNumber(number + 1);
else setNumber(number - 1);
setClick(!click);
};
return (
<>
<h1>올해도 아좌좌 ㅋ_ㅋ</h1>
<AjajaButton isFilled={click} onClick={handleClick}>
{number}
</AjajaButton>
</>
);
```
- 확장성을 일단 덜어냈습니다.  d59af76

[혜수] - 아좌좌 button 공통 컴포넌트

---

src/components/Modal/Modal.tsx
src/components/Modal/index.scss
src/components/index.ts

close #10 
https://github.com/New-Barams/this-year-ajaja-fe/assets/67812466/4dc1d714-d15f-4bd3-9c57-9af2d4f8682a
- 기본 모달 구현 완료
- 모달 외부 클릭시 모달 닫힘 기능 추가
```ts
interface ModalProps {
onClickYes: () => void; //네 클릭했을 때 동작
onClickNo: () => void; //아니오 클릭했을 때 동작
children: React.ReactNode;
}
```
```tsx
'use client';
import { Button } from '@/components';
import Modal from '@/components/Modal/Modal';
import { useState } from 'react';
import './index.scss';
const [open, setOpen] = useState(false);
const handleModal = () => {
setOpen(!open);
};
return (
<>
<Button
background="primary"
color="white-100"
size="lg"
border={false}
onClick={handleModal}>
모달
</Button>
{open && (
<Modal onClickYes={handleModal} onClickNo={handleModal}>
다른 모든 리마인드 메세지가 해당 메세지와 동일한 내용으로 …
```

[혜수] - 공통 modal 컴포넌트 완성

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/index.scss
src/components/Icon/Icon.tsx

close #30
<br>
https://github.com/New-Barams/this-year-ajaja-fe/assets/31370590/e0a73ae7-dc7f-41b0-a7b7-932636be55fa
+ 여러 option 중 한 개의 option을 선택할 수 있는 dropdown 컴포넌트입니다. 
+ 호출 시, 기본으로 선택될 default 값을 넣어줘야 합니다. 
+ 컴포넌트 바깥을 클릭하면 dropdown이 닫힙니다. 
<br>
```tsx
const [period, setPeriod] = useState(12); // 기본 option 값 = 12
const PERIOD_OPTIONS = [
{ value: 12, name: '1년' },
{ value: 6, name: '6개월' },
{ value: 3, name: '3개월' },
{ value: 1, name: '1개월' },
];
return (
<div>
<Dropdown
options={PERIOD_OPTIONS}
selectedValue={period}
setSelectedValue={setPeriod}
/>
</div>
);
}
```
```tsx
interface DropdownProps {
options: optionsType[]; // name, value 속성을 갖고 있는 option 객체 => 위 사용 예시 참고 
selectedValue: number; // dropdown을 통해 변경되기를 원하는 상태 state 값 
setSelectedValue: …
```

[민우] - Dropdown 컴포넌트 구현

---

package-lock.json
package.json
src/components/CircleProgressBar/CircleProgressBar.tsx
src/components/CircleProgressBar/index.scss
src/constants/color.ts
src/constants/index.ts

close #36 
<br>
<br>
```tsx
interface CircleProgressBarProps {
isFeedbackDone: boolean; // 피드백했는지 여부
percent?: number; // 피드백 o 시 -> 달성률
onClick?: () => void; // 피드백 x 시 -> 해당 리마인드에 대한 평가모달 호출해주는 함수
}
```
<br>
```tsx
'use client';
import CircleProgressBar from '@/components/CircleProgressBar/CircleProgressBar';
return (
<div style={{ margin: '100px' }}>
<CircleProgressBar
isFeedbackDone={false}
percent={66}
onClick={() => {
console.log('클릭');
}}
/>
<div style={{ height: '20px', width: '100px' }}></div>
<CircleProgressBar
isFeedbackDone={true}
percent={66}
onClick={() => {
console.log('클릭');
}}
/>
</div>
);
}
```

[민우] - CircleProgressBar 컴포넌트 구현

---

src/components/InputTag/InputTag.tsx
src/components/Modal/Modal.tsx

[노철] - use client 누락

---

src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalEvaluate.tsx
src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalRadio.tsx
src/app/(header)/plans/[planId]/_components/ModalEvaluate/index.scss
src/components/Dropdown/index.scss
src/components/Icon/Icon.tsx
src/components/Modal/Modal.tsx
src/components/Modal/ModalBasic.tsx
src/components/Modal/index.scss
src/components/PlanInput/index.scss
src/components/index.ts
src/hooks/useModalClose.ts
src/styles/class/mixin.scss
src/styles/standard.scss
src/types/IconName.ts

close #38 
- 모달 컴포넌트 분리 작업(모달 외형 & 내부 분리)
- useModalClose hook 생성
- error, warning, close 아이콘 추가 
- 평가 모달 완성 ( 라디오 버튼 이용)
- --border-weight -> --border-width로 변경 
https://github.com/New-Barams/this-year-ajaja-fe/assets/67812466/66496cea-34b6-45e5-8912-3d9bf5ad3a0a

[혜수] - 평가 모달 생성

---

src/components/InputTag/InputTag.tsx

[노철] - inputTag 에러

---

src/app/(header)/create/index.scss
src/app/(header)/create/page.tsx
src/app/(header)/edit/[planId]/index.scss
src/app/(header)/edit/[planId]/page.tsx
src/app/(header)/plans/[planId]/index.scss
src/app/(header)/plans/[planId]/page.tsx
src/components/AjajaButton/AjajaButton.tsx
src/components/Button/Button.tsx
src/components/Remind/WritableRemind/WritableRemind.tsx
src/components/WritablePlan/WritablePlan.tsx

close #77 
작성 페이지, 수정 페이지 모두 서버 연결 전까지 완료했습니다 !

[민우] - 작성 페이지, 수정 페이지 구현

---

src/app/(header)/my/_components/ModalVerification.tsx
src/app/(header)/my/_components/index.scss
src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx

close #75 
내용
마이페이지 입니다. 기본 로직만 작동하도록 했습니다. 
모달 잘썼습니다.👍👍👍

[노철] - 마이페이지

---

src/app/(header)/explore/_components/Card/Card.tsx

close #88 
아좌좌가 0이어도 자몽색으로 fill 해주었습니다.

[혜수] - 다른 계획 둘러보기 아좌좌 색 통일(자몽색)

---

src/components/AjajaButton/AjajaButton.tsx

close #87
1000 단위 K 제거했습니다. (아주 간단)

[혜수] - 아좌좌 1000단위 K 제거

---

.github/actions/slack-notify.yml
.github/workflows/merge-to-main.yml

close #95 
- 머지 성공, 실패시 알려주는 slack 알림 봇 추가
- main으로 매주 월, 수 9시에 자동 배포 action 추가
만약에 이상하게 작동하면 내일 당장 지우겠습니당...!

[혜수] - Github Actions dev -> main 머지 자동화

---

src/app/layout.tsx

[전체] - meta tag 삭제 

---

next.config.js

[혜수] - Mixed Content 문제 rewrite 이용

---

next.config.js
src/app/layout.tsx

[전체] - 배포 

---

next.config.js

💩 : #111 rewrite 제거

---

src/apis/client/getTokenWithCode.ts
src/constants/api.ts

close #117
-로그인  api 함수 상수화했습니다

[노철]-  로그인 api 함수 상수화

---

src/apis/client/getAllPlans.ts
src/apis/client/getAllPlansMock.ts
src/apis/client/postAaja.ts
src/apis/server/getMyPlans.ts
src/app/(header)/explore/_components/Card/Card.tsx
src/app/(header)/explore/_components/ExplorePlans.tsx
src/app/(header)/explore/_components/Plans/Plans.tsx
src/app/(header)/explore/_components/Tab/Tab.tsx
src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/home/_components/NewPlan/NewPlan.tsx
src/app/(header)/home/_components/NewPlan/index.scss
src/app/(header)/home/page.tsx
src/components/AjajaButton/AjajaButton.tsx
src/constants/api.ts
src/hooks/apis/plans/useAllPlansQuery.ts
src/types/apis/plan/GetAllPlans.ts
src/types/apis/plan/GetMyPlans.ts

close #89 
- 내 계획 전체 불러오기 API
- 공개한 전체 계획 API
- 아좌좌 API
API가 잘 작동하는 것을 확인했습니다.
현재 공개한 전체 계획 API를 가져오는 부분에서 아좌좌 버튼이 최신순일 때(useState 설정할 때 넣은 기본 값)로 숫자가 고정되어있는 문제가 있습니다 😢

[혜수] - API 연결 작업 준비 - Hook 만들어 놓기

---

src/apis/client/postFeedback.ts
src/constants/api.ts
src/hooks/apis/feedback/usePostFeedbackMutation.ts
src/types/apis/feedback/PostFeedbaks.ts

close #123 
- 피드백 API 테스트를 위해 API 생성 완료
- postFeedback api 추가
- usePostFeedbackMutation 생성

[혜수] - 피드백 API 생성 

---

src/components/AjajaButton/AjajaButton.tsx
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
src/hooks/apis/usePostAjajaMutation.ts

close #146
- usePostAjajaMutation 추가
- ajaja 버튼 planId 추가 
- ajaja 버튼 계획 단건 조회와 연결 완료

[혜수] - Ajaja 버튼에 planId 넣도록 수정

---

src/apis/client/postVerify.ts
src/app/(header)/my/page.tsx
src/app/(headerless)/oauth/hooks/useOauthPage.ts
src/components/ModalVerification/ModalVerification.tsx
src/constants/login.ts

close #150  
- 인증과정시 유효성검사 결과 안내 문구 추가 
- 로그인 , 로그아웃시 모두 /oauth로 리다이렉트로 변경, 안에서 분기 처리

[노철] - 로그아웃, 회원탈퇴 리팩토링 

---

src/apis/client/postLogin.ts
src/constants/api.ts
src/types/apis/users/GetTokenWithCoin.ts

close #159 
- 로그인 실제 api로 변경
- 변경 내용 반영

[노철] - 실제 로그인 연결

---

src/app/(header)/home/_components/MyPlan.tsx

close #162 
- 계획이 비어있을 때 email_isVerified 체크 오류 해결

[혜수] - 계획이 비어있을 때 email_isVerified 체크 오류 해결

---

src/app/(header)/edit/[planId]/page.tsx
src/components/Dropdown/index.scss
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
src/hooks/apis/feedback/usePostFeedbackMutation.ts
src/hooks/apis/useDeletePlanMutation.ts
src/hooks/apis/useEditPlanMutation.ts
src/hooks/apis/useGetRemindQuery.ts
src/hooks/apis/usePostNewPlanMutation.ts
src/hooks/apis/useToggleAjajaNotificationMutation.ts
src/hooks/apis/useToggleIsPublicMutation.ts
src/hooks/apis/useToggleIsRemindable.ts

[민우] - mutation 무효화 로직 추가

---

src/app/(header)/home/_components/MyPlan.tsx

close #179 
- handleSetVerifiedEmail Promise.all로 변경

[혜수] - handleSetVerifiedEmail Promise.all로 변경

---

src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/components/ModalVerification/ModalVerification.tsx
src/components/ModalVerification/index.scss

close #177 
- 이름 간격 변경
- 이름 아래 경고문 간격 추가
- 이메일 변경하기 버튼 색 변경
-  인증 모달에서 인증 완료 버튼 visible 변경
이거 텍스트들 줄바꿈 처리하고 싶은데 어떻게 해야될까요?

[노철] - 마이페이지 스타일 수정

---

src/components/Button/index.scss

close #191 
- 버튼 sm 크기 변경 (패딩 3px 10px로 변경)

[혜수] - 계획 주기 확정 버튼 sm 크기 키우기

---

src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/components/ModalVerification/ModalVerification.tsx
src/components/ModalVerification/index.scss

close #198 
- modal 크기 변경
- 인증완료 버튼 비활성화로 변경
-  이메일 인증 여부에 따라 버튼 문구 변경

[노철] - 이메일 인증 모달 style 수정 

---

src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/app/(headerless)/login/index.scss
src/app/(headerless)/login/page.tsx
src/components/InputTag/index.scss
src/components/ModalVerification/ModalVerification.tsx
src/components/ModalVerification/index.scss
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
src/components/Tag/Tag.tsx
src/components/Tag/index.scss
src/components/WritablePlan/WritablePlan.tsx

close #209 
- 마이페이지 위치 조정
- 태그 크기 조절
- 인풋 태그 패딩 적용
- 인풋 태그 안내 문구 변경
- 인증 모달  버튼, 인풋 패딩 적용
- 가이드라인 버튼 (작성하기에 안보이는 문제 )
- 인증 번호 확인 안보이게 변경
- 로그인 페이지 높이 적용
- 토글 버튼 옆 text 폰트 사이즈 통일

[노철] - 스타일 수정 

---

src/app/(header)/my/page.tsx
src/app/(headerless)/oauth/hooks/useOauthPage.ts

close #216 
로그인 관련 토스트 적용
로컬에서는 reactStrictMode때문에 두번씩 호출됩니다.

[노철] - 로그인 관련 토스트 적용

---

src/hooks/apis/useDeletePlanMutation.ts
src/hooks/apis/useEditPlanMutation.ts
src/hooks/apis/usePostFeedbackMutation.ts
src/hooks/apis/usePostNewPlanMutation.ts

[민우] - 특정 api 호출 실패 시 error 토스트 연결 

---

src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/home/_components/NewPlan/NewPlan.tsx
src/app/(header)/home/_components/NewPlan/index.scss
src/app/(header)/home/_components/Plan/Plan.tsx
src/app/(header)/home/_components/Plan/index.scss
src/app/(header)/home/_components/index.scss
src/components/Tag/Tag.tsx

close #218 
- 계획 원형 높이 안맞는 문제 수정
- 태그 높이 좀 줄이기
- 전체 달성률과 프로그래스바와 좀 더 가까이
- 제목 text-overflow … 처리

[혜수] - 내 계획 페이지 스타일 수정

---

src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/components/ModalVerification/ModalVerification.tsx
src/components/ModalVerification/index.scss

close #234 
마이페이지 디자인 수정
인증 모달 디자인 수정

[노철] - 마이페이지 디자인 수정

---

src/app/(header)/_components/Content.tsx
src/app/(header)/explore/_components/ExplorePlans.tsx
src/app/(header)/explore/_components/index.scss
src/hooks/useScroll.ts

close #238 
- useScroll hook 생성
- explore에서 훅 적용

[혜수] - 무한스크롤 되지 않는 오류 해결

---

README.md

README 작성 main branch 반영  

---

src/app/(header)/my/page.tsx
src/app/_components/Navigation/Navigation.tsx
src/app/_components/Navigation/index.scss
src/app/_components/index.scss
src/app/layout.tsx
src/components/Icon/Icon.tsx
src/types/IconName.ts

close #261 
- 네비게이션바 추가
- 로그인 유무에 따라 마이페이지, 로그인 변경
- 경로마다 네비게이션바 색상 변경
- 로그아웃할 때 auth 쿠키 제거하는 부분 추가했습니다.  296b3ce(삭제 안하면 네비게이션바에서 로그인으로 바로 변경이 안됩니다)

[혜수] - 네비게이션바 추가

---

src/app/(header)/my/page.tsx
src/app/(header)/plans/[planId]/page.tsx
src/app/_components/Navigation/Navigation.tsx
src/app/_components/Navigation/index.scss
src/app/_components/index.scss
src/app/layout.tsx
src/components/Icon/Icon.tsx
src/components/Modal/ModalBasic.tsx
src/components/Modal/index.scss
src/components/Remind/WritableRemind/WritableRemind.tsx
src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
src/types/IconName.ts

close #260 
- 모바일 관련 너비 수정
- 기본 모달 스타일 변경 완료
- 기본 모달 버튼 문구 추가 및 사용하는 컴포넌트들 수정 완료
모달 밖을 누르면 나가지는걸 다른 유저도 알 수 있을지 궁금합니다.
따로 나가는 버튼이 없어서 헷갈릴지 아닐지 고민이 있습니다..
- ModalExit는 지금 모달 확인이 안되어서 좀 나중에 수정하겠습니다!
- 평가 모달도 우선순위는 아닌것 같아 추후 수정하겠습니다

[혜수] - 모달 수정

---

src/apis/axiosInstanceClient.ts

close #267 
- 토큰 재발행시 관리가 안되던 에러가 있어서 추가했습니다. 
- 재발행, 리트라이시 에러가 생긴다면 재로그인하도록 변경

[노철] - 토큰 재발행 에러 추가 

---

src/apis/axiosInstanceClient.ts

close #269 
- axios error interceptor에서 처리가 필요 없는 error 리턴값 변경

[노철] - axios interceptor 에러 수정 

---

src/components/WritablePlan/WritablePlan.tsx

close #272 
- inputTag에 불필요한 props 제거

[노철] - build 에러 제거

---

src/components/KakaoShareButton/KakaoShareButton.tsx

[노철] - 타입 에러 수정

---

src/app/not-found.scss
src/app/not-found.tsx
src/components/BasicError/BasicError.tsx
src/components/BasicError/index.scss

close #301 
기존 디자인에서 비율만 맞도록 수정해놓았습니다 !!

[민우] - Error 컴포넌트 및 NotFound 컴포넌트 디자인

---

src/app/_components/LandingPage/LandingPage.tsx

close #302 
- 아이콘 색상 오렌지 -> 자몽

[혜수] - 랜딩페이지 아이콘 색상 변경

---

src/stores/canMakeNewPlanStore.ts

close #304 
- `default : false -> true`로 변경해 해결

[혜수] - 비회원일 때 계획 작성 토스트 오류 해결 

---

src/app/(header)/explore/_components/ExplorePlans.tsx
src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/app/(header)/plans/[planId]/index.scss
src/app/(header)/plans/[planId]/page.tsx
src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
src/app/(headerless)/login/index.scss
src/app/(headerless)/login/page.tsx
src/components/KakaoShareButton/KakaoShareButton.tsx
src/components/KakaoShareButton/index.scss
src/components/PlanInput/index.scss
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
src/components/ToTopFloatingButton/ToTopFloatingButton.tsx
src/components/ToTopFloatingButton/index.scss

close #299 
- 슬라이드 이미지 크기 수정
- 로그인 페이지 height, scroll 수정
-로그인페이지 로고 변경
- 마이페이지 스크로 ,height 적용
- 마이페이지 welcome 문구 분리
- 로그아웃 , 회원탈퇴 구분, 분리
- 로그아웃, 회원탈퇴 hover
- 아이템 별 분리
- 계획 스크롤 적용, height 수정
- 상세페이지 description 컬러 변경
- 카카오 고유 버튼 이미지
- floating button 위치 조정

[노철] - 페이지 디자인 수정

---

src/styles/class/font-size.scss

close #312 
- 작은 화면일 때 xl 폰트 사이즈 1.75rem으로 변경

[혜수] - 작은 화면일 때 xl 폰트 사이즈 1.75rem으로 변경

---

src/app/(header)/plans/[planId]/index.scss
src/app/(header)/plans/[planId]/page.tsx
src/app/(header)/plans/edit/[planId]/page.tsx
src/app/(headerless)/login/index.scss
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx

close #311
- 로그인 페이지 top마진 변경
- 계획 수정, 삭제 구분선 변경
- 계획 수정 페이지 버튼 border 변경
- 피드백 보기 비활성화

[노철] - 로그인 페이지 마진 변경

---

src/app/(header)/my/index.scss
src/app/(header)/plans/[planId]/index.scss
src/app/(header)/plans/[planId]/page.tsx
src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
src/app/(headerless)/login/index.scss

close #315 
- 로그인 스크롤 제거
- 계획 상세페이지 피드백 버튼 비활성화
- 마이페이지 갭 설정

[노철] - 마이페이지 갭 변경

---

src/apis/axiosInstanceClient.ts
src/app/(headerless)/oauth/hooks/useOauthPage.ts
src/constants/cookie.ts
src/stores/authStore.ts

close #326 
쿠키 설정 시간을 상수화 하고 적용했습니다

[노철] - 쿠키 max-age 변경

---

src/components/Modal/ModalBasic.tsx

close #328 
- 모달 기본 폰트 base로 변경

[혜수] - 모달 기본 폰트 base로 변경

---

src/app/(header)/explore/_components/Card/Card.tsx
src/types/apis/plan/GetAllPlans.ts

close #329 
- 다른 계획 둘러보기 API 아이콘 적용

[혜수] - 다른 계획 둘러보기 API 아이콘 적용

---

src/types/apis/plan/GetMyPlans.ts

close #337 
- Plan type API에 맞게 수정

[혜수] - Plan type API에 맞게 수정

---

src/apis/axiosInstanceClient.ts

close #341 
리이슈 조건을 잘 못 설정해서 무한 리이슈가 발생했었습니다. 
조건식 변경

[노철]- 토큰 재발행 재귀 호출

---

src/hooks/useWritablePlan.ts
src/types/Plan.ts

[민우] - useWritablePlan에서 계획 수정 data에 대한 type => EditPlanData로 수정

---

src/app/(header)/plans/[planId]/page.tsx
src/stores/isMyPlanStore.ts

close #348
- isMyPlanStore 구현
- '/plan/[id]' 페이지 접속시 store 상태 변경, 나가면 default 값으로 변경

[노철]- isMyPlan store 

---

src/app/(header)/plans/edit/[planId]/page.tsx

close #356 
- 기존에 잘못 적용된 접근 권한 설정 변경

[노철]- 타인 수정 페이지 접근 막기

---

src/app/_components/Navigation/Navigation.tsx

close #360 
- 계획 수정할 때 nav 홈으로 변경

[혜수] - 계획 수정할 때 nav 홈으로 변경

---

src/app/(header)/reminds/edit/[planId]/page.tsx

[민우] - 리마인드 수정 후 해당 리마인드 페이지로 돌아가도록

---

src/constants/cookie.ts

[노철] - 쿠키 저장 시간 변경

---

src/apis/client/deletePlan.ts
src/apis/client/editPlan.ts
src/apis/client/postNewPlan.ts

[민우] - 계획 작성, 삭제, 수정 시 header 값 오류

---

src/apis/client/deletePlan.ts
src/apis/client/editPlan.ts
src/apis/client/postNewPlan.ts
src/constants/cookie.ts

[hotfix] - 계획 작성, 수정, 삭제 시 header 

---

src/app/(headerless)/login/page.tsx

[hotfix] - 로그인 페이지 오타 수정

---

src/apis/axiosInstanceClient.ts
src/utils/checkIsTokenExpired.ts
src/utils/checkTokenExp.ts

close #386 
- 토큰 비교 로직 변경
- 토큰 비교 함수명 변경

[노철] - 토큰 재발행 에러

---

src/components/CreatePlanIcon/CreatePlanIcon.tsx
src/components/CreatePlanIconExample/CreatePlanIconExample.tsx

[민우] - 계획 작성 시 아이콘 선택 로직 수정

---

src/app/(header)/plans/[planId]/page.tsx

[노철] - 계획 상세 피드백 버튼 활성화

---

src/app/(headerless)/notice/index.scss
src/app/(headerless)/notice/page.tsx

close #428 
공지사항 페이지에 텍스트 추가 및 스크롤 적용했습니다. 
https://github.com/New-Barams/this-year-ajaja-fe/assets/31370590/99c9baa0-691a-4a3a-b676-fe5be2b89af6

[민우] - 공지사항 페이지 내용 추가 

---

src/styles/webkit.scss

close #420 
- 스크롤바가 항상 보이도록 변경
hook은 다른분들 작업 끝나면 한번에 제거하겠습니다!

[혜수] - 스크롤바가 항상 보이도록 변경

---

src/app/_components/Navigation/Navigation.tsx

close #419 
- 네비게이션바 아이콘 색상이 바뀔 때 글자 색상은 변경되지 않는 문제 해결

[혜수] - 네비게이션바 아이콘 색상이 바뀔 때 글자 색상은 변경되지 않는 문제 해결

---

src/app/_components/Navigation/Navigation.tsx

close #436 
네비게이션 잘못 들어간 코드 삭제

[혜수] - 네비게이션 잘못 들어간 코드 삭제

---

src/app/feedback/[planId]/_components/index.scss

close #438 
- 피드백 스크롤 다른 페이지보다 얇은 문제 해결
기존 스크롤
변경

[혜수] -  피드백 스크롤 다른 페이지보다 얇은 문제 해결

---

src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/app/(header)/plans/[planId]/index.scss
src/app/(header)/plans/[planId]/page.tsx
src/app/(header)/plans/edit/[planId]/index.scss
src/app/(header)/plans/edit/[planId]/page.tsx

close #440 
- 마이페이지  top 패딩 추가
- 마이페이지 스크롤 위치 조정
- 계획 상세 스크롤 위치 수정
- 계획 수정 스크롤 위치 수정

[노철] - 스크롤 위치 수정

---

src/app/(header)/plans/edit/[planId]/index.scss
src/app/(header)/plans/edit/[planId]/page.tsx
src/components/TagInput/TagInput.tsx
src/components/TagInput/index.scss

close #441 
- 태그 인풋 크기 변경
- 태그 인풋 플레이스 홀더 패딩 추가 
- 올라갔을때 글자색 변경, 보더 굵기 변경

[노철]-태그 인풋 수정

---

src/app/_components/Navigation/Navigation.tsx

close #446 
- 피드백하기 nav에서 삭제
- 작성 기간이 아닐 때 계획 작성을 누르면 토스트 알림 추가

[혜수] - 피드백하기 nav에서 삭제

---

src/apis/client/postFeedbacks.ts

♻️ : #452 - postfeedbaks 오타 수정

---

src/components/FeedbackItem/FeedbackItem.tsx

[혜수] - 피드백 퍼센트 관련 잘못된 조건 수정 완료

---

.github/workflows/nodejs.yml

close #472 
- PR시 build 작업 추가 (CI)

[혜수] - PR시 build 작업 추가 (CI)

---

.github/workflows/nodejs.yml

close #472 
- 브랜치명 실수했습니다 😭 develop -> dev로 변경했습니다.

[혜수] - 브랜치명 develop -> dev로 변경

---

.github/workflows/sync-fork.yml

[혜수] - 포크 자동화 ACTION 추가
