New-Barams/this-year-ajaja-fe

src/components/Button/Button.tsx
src/components/Button/index.scss
src/styles/class/border.scss
src/styles/class/mixin.scss
src/styles/variables.scss
src/types/Color.ts

close #8
- 공통 버튼 컴포넌트 
- border 공통 css 추가했습니다.
- Color type에 primary 없어서 추가했습니다.
- 사용법
``` tsx
'use client';
import Button from '@/components/Button/Button';
const click = () => {
alert('hi!');
};
return (
<>
<h1>올해도 아좌좌 ㅋ_ㅋ</h1>
<Button
background="primary"
color="white-100"
fontSize="2xl"
size="lg"
onClick={click}>
삭제
</Button>
<Button background="primary" color="white-100" fontSize="xl" size="md">
계획 수정 완료
</Button>
<Button background="primary" color="white-100" fontSize="base" size="sm">
확정
</Button>
<Button
background="white-100"
color="primary"
fontSize="sm"
size="sm"
onClick={click}>
취소
</Button>
</>
);
}
```

[혜수] - 공통 버튼 컴포넌트 완성

---

src/components/AjajaButton/AjajaButton.tsx
src/hooks/useDebounce.ts

close #27 
- 디바운스 훅 추가
- 아좌좌 버튼의 상태 컴포넌트 안으로 이동 
캡슐화 해놨습니다.
```tsx
interface AjajaButtonProps {
isFilled: boolean;
ajajaCount: number;
}
<AjajaButton isFilled={false} ajajaCount={0} />
```
훅으로 빼놔서 어제 멘토님이 말해주신 방법이 적용이 잘 안되어서 일단 컴포넌트 안에 디바운스를 넣어놨습니다.

[혜수] - 공통 아좌좌 버튼 상태 컴포넌트 안으로 이동

---

src/components/Button/Button.tsx
src/components/Button/index.scss
src/styles/class/border.scss

close #31 
- 버튼 컴포넌트 props 간소화
- global css border-none, border-round 추가(기존에 작성했던 코드와 충돌 x)
- 버튼 컴포넌트 새로 추가된 box-sizing에 맞춰 수정
border-none과 round는 리팩토링할 때 변경하셔도 될것같습니다.
```tsx
interface ButtonProps {
background: Color;
color: Color;
size: 'lg' | 'md' | 'sm';
border: boolean;
onClick?: () => void;
children?: React.ReactNode;
}
<Button
background="primary"
color="white-100"
size="md"
border={false}>
아니오
</Button>
```

[혜수] - 버튼 컴포넌트 리팩토링

---

src/components/Icon/Icon.tsx
src/components/RemindInput/index.scss
src/components/WritableRemindItem/WritableRemindItem.tsx
src/components/WritableRemindItem/index.scss
src/components/index.ts
src/types/IconName.ts

close #47 
https://github.com/New-Barams/this-year-ajaja-fe/assets/31370590/c88f0c0f-b05a-401b-b5bb-685d4d451ca9
+ 계획 작성 페이지, 계획 수정 페이지에서 사용되는 수정 가능한 리마인드 아이템 컴포넌트입니다. 
+ 리마인드 메세지가 입력되지 않았다면 경고 문구를 띄워지고, 조금이라도 입력된다면 없애줍니다.
+ 만약 첫번째 리마인드 아이템이라면 현재 메세지로 나머지 메세지를 다 동기화할 수 있는 체크박스를 선택가능합니다.
+ 체크박스 해제 시, 그 이후부터는 동기화가 멈춥니다. 
```tsx
interface WritableRemindItemProps {
remindMonth: number; // 리마인드 받는 월 ex) 6
remindDay: number; // 리마인드 받는 날 ex) 15
remindMessage: string; // 리마인드 메세지 ex) 미래의 민우야
handleChangeRemindMessage: (text: string) => void; // 리마인드 메세지 업데이트하는 핸들러  => 하위 RemindInput으로 전달될 것
makeAllRemindMessageSame?: () => void; // 동일한 리마인드 메세지 받기 => 이게 넘어온다면 첫번째 아이템이라는 것
}
```
```tsx
const [remindMessage, setRemindMessage] = useState('');
useEffect(() => { …
```

[민우] - 작성 가능 리마인드 아이템  컴포넌트 구현

---

package-lock.json
package.json
src/apis/axiosInstance.ts
src/constants/api.ts
src/hooks/apis/plans/useAllPlansQuery.ts
src/hooks/apis/users/useRefreshNameMutation.ts
src/stores/authStore.ts
src/types/axios/index.d.ts

close #55 
- localstorage -> cookie로 변경
- axiosInstance 생성
- useRefreshNameMutation, useAllPlansQuery 임시 생성
노션에 컴포넌트 사용 설명 써놨습니다
노철님 
쿠키로 변경하면서 useAuth 부분 state가 이제 필요 없을 수도 있을 것 같습니다. 한번 확인해보시면 좋을 것 같아요.

[혜수] - 인스턴스 생성

---

src/components/InputTag/InputTag.tsx
src/components/InputTag/index.scss
src/components/WritablePlan/WritablePlan.tsx
src/components/WritablePlan/index.scss

close #70
받고있는 props
실제 사용 예시
아직은 단순 로직만 넣었습니다.

[노철] - 수정, 쓰기를 위한 계획 컴포넌트

---

src/apis/client/getAllPlans.ts
src/app/(header)/_components/index.scss
src/app/(header)/explore/_components/Card/Card.tsx
src/app/(header)/explore/_components/Card/index.scss
src/app/(header)/explore/_components/ExplorePlans.tsx
src/app/(header)/explore/_components/Plans/Plans.tsx
src/app/(header)/explore/_components/Plans/index.scss
src/app/(header)/explore/_components/Tab/Tab.tsx
src/app/(header)/explore/_components/Tab/index.scss
src/app/(header)/explore/_components/index.scss
src/app/(header)/explore/page.tsx
src/components/AjajaButton/AjajaButton.tsx
src/components/AjajaButton/index.scss
src/hooks/apis/plans/useAllPlansQuery.ts
src/provider/TanstackQueryProvider.tsx
src/types/apis/plan/GetAllPlans.ts

close #53 
- 탭, 정렬 추가
- 카드 컴포넌트 생성
- ajaja 버튼 수정 (배경색 제거 및 글자 스타일 수정 & classNameList 추가)
- 카드 나름 반응형 구현...?
- useAllPlansQuery 추가 -> 민우님 PR 참고해서 키값 수정필요할 것 같습니다.
- 스크롤 border 내부로 변경했습니다. -> 이제 스크롤 디자인 안어울리는거같아요.. 
카드에서 아좌좌는 아직 못누를 것 같습니다.
만약 누르게 하고싶다면 자신이 눌렀는지 안눌렀는지 로그인 여부 확인에 따라 불러오는 API가 달라져야해서 백엔드에 요청이 필요합니다.
-> 현재 disable 해놓은 상태

[혜수] 다른 계획 둘러보기 구현

---

src/apis/axiosInstanceClient.ts
src/apis/axiosInstanceServer.ts
src/apis/client/deletePlan.ts
src/apis/client/editPlan.ts
src/apis/client/getAllPlans.ts
src/apis/client/getRemindAfterSeason.ts
src/apis/client/getRemindSeason.ts
src/apis/client/postNewPlan.ts
src/apis/client/toggleAjajaNotification.ts
src/apis/client/toggleIsPublic.ts
src/apis/client/toggleIsRemindable.ts
src/apis/server/getMyPlans.ts
src/app/(headerless)/oauth/hooks/useOauth.ts
src/constants/api.ts

close #62 
`DOMAIN.PUT_PLANS_SWITCH_REMINDABLE(id)` 이런식으로 사용하시면 됩니다
기존에 작성되어있던 API들 상수로 변경했습니다
환경 변수 `NEXT_PUBLIC_BASE_URL`로 수정해주세요! 
+ 노철님 제가 노션 한번 더 수정했습니다..! 👍

[혜수] - API 엔드 포인트 상수화 작업

---

src/apis/client/deletePlan.ts
src/apis/client/editPlan.ts
src/apis/client/getRemindAfterSeason.ts
src/apis/client/getRemindSeason.ts
src/apis/client/postNewPlan.ts
src/app/(header)/create/page.tsx
src/app/(header)/edit/[planId]/page.tsx
src/app/(header)/plans/[planId]/page.tsx
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/constants/api.ts
src/hooks/apis/useGetRemindQuery.ts
src/hooks/apis/usePostNewPlanMutation.ts
src/types/apis/plan/EditPlan.ts
src/types/apis/plan/PostNewPlan.ts
src/types/components/Remind.ts
src/utils/changeRemindTimeToNumber.ts
src/utils/changeRemindTimeToString.ts
src/utils/currentMonth.ts

close #86
계획 작성, 상세, 수정 페이지에서 쓰이는 API들을 현재 mock으로 연결해 두었습니다.  아직 연결하지 못한 API들은 노철님, 혜수님이 훅 구현해주시면 바로 연결하겠습니다 !!
**작성 페이지**
**상세 페이지**
**수정 페이지**

[민우] - 작성, 상세, 수정 페이지 서버 통신 API 연결 

---

src/app/(header)/home/_components/NewPlan/NewPlan.tsx
src/app/(header)/home/page.tsx
src/utils/checkThisYear.ts

close #97 
- 현재 년도 확인 함수 추가
- 현재 년도 계획이 비어있을 때 빈 배열 추가 로직 추가
- 시즌, 비시즌 구분해 작성 컴포넌트 변경 완료

[혜수] - 내 계획 페이지 추가 수정

---

package-lock.json
package.json
src/apis/client/deletePlan.ts
src/apis/client/editPlan.ts
src/apis/client/getRemindAfterSeason.ts
src/apis/client/getRemindSeason.ts
src/apis/client/postNewPlan.ts
src/app/(header)/create/page.tsx
src/app/(header)/edit/[planId]/page.tsx
src/app/(header)/plans/[planId]/page.tsx
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/constants/api.ts
src/hooks/apis/useGetRemindQuery.ts
src/hooks/apis/useToggleAjajaNotificationMutation.ts
src/types/apis/plan/EditPlan.ts
src/types/apis/plan/PostNewPlan.ts
src/types/apis/remind/getRemind.ts
src/types/components/Remind.ts
src/utils/changeRemindTimeToNumber.ts
src/utils/changeRemindTimeToString.ts
src/utils/checkIsSeason.ts
src/utils/getUserIdFromJWT.ts

close #119
현재 작성, 수정,  상세페이지에서 사용되는 
모두 실제 API로 잘 동작하는 것 확인했습니다 !  노철님 혜수님이 계획 단건 조회 API와 피드백 반영 API가 구현해주면 => 각 페이지에 제가 연결하면 될 것 같습니다 ! 위의 API가 동작은 하지만, 아직까지는 로딩 처리, 에러 처리, API 호출로 발생하는 자잘한 이슈들이 있는 상태라 차차 해결하겠습니다,,,, ㅎㅎㅎ
참고 : 986317ccbbd66d5292b03a59861f0bf92c953e6e
이를 이용해 쿠키의 userId vs 특정 계획의 userId 비교해 내 계획인지 판단하는 훅도 구현 예정입니다 !!

[민우] - 실제 API 연결 및 오류 해결 

---

src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/home/_components/Plan/Plan.tsx

close #124
- 내 계획 페이지 계획 클릭시 올바른 planId 경로로 들어가도록 추가

[혜수] - 내 계획 페이지 계획 클릭시 올바른 planId 경로로 들어가도록 추가

---

src/apis/client/getMyPlans.ts
src/app/(header)/home/page.tsx
src/hooks/apis/plans/useGetMyPlansQuery.ts

close #127 
- 내 계획 페이지 api 클라이언트 컴포넌트로 변경
- react query 적용

[혜수] - 내 계획 페이지 API server -> client로 변경

---

src/app/(header)/_components/Header/Header.tsx
src/app/(header)/_components/LinkIconText/LinkIconText.tsx

close #129 
- LinkIconText border 속성 추가
- 헤더 로그인 여부에 따라 텍스트 변경 완료

[혜수] - 로그인 여부에 따라 헤더 텍스트 변경

---

src/apis/client/getTokenWithCode.ts
src/constants/api.ts
src/types/apis/login/getTokenWithCoin.ts

close #133 
로그인api 방식이 변경됐습니다. 
기존=> query로  인가코드 전달
변경=> requestBody로 인가코드, 리다이렉트 주소 전달

[노철] - 로그인 방식 변경

---

package-lock.json
package.json
src/app/(header)/edit/[planId]/page.tsx
src/app/(header)/plans/[planId]/page.tsx
src/app/loading.scss
src/app/loading.tsx
src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
src/constants/api.ts
src/hooks/apis/useGetPlanQuery.ts
src/utils/checkIsMyPlan.ts
src/utils/checkIsSeason.ts

[민우] - 상세 페이지 초기 진입 로직 추가 및 임시 로딩 페이지 구현

---

src/app/(header)/_components/index.scss
src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/home/_components/index.scss

close #132 
- 이메일 인증 여부 추가했습니다.
- 헤더의 최상위 레이아웃 height 조절했고, 스크롤 요소는 넘칠때만 적용되도록 했습니다.

[혜수] - 내 계획 페이지 이메일 인증 여부 추가 

---

src/app/(header)/create/page.tsx
src/app/(header)/edit/[planId]/page.tsx
src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/plans/[planId]/page.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/components/Remind/WritableRemind/WritableRemind.tsx
src/hooks/apis/useDeletePlanMutation.ts
src/hooks/apis/useEditPlanMutation.ts
src/hooks/apis/useGetPlanQuery.ts
src/hooks/apis/useGetRemindQuery.ts
src/hooks/apis/usePostNewPlanMutation.ts
src/hooks/apis/useToggleIsRemindable.ts
src/middleware.ts

close #137 
+ `/` 페이지 접근 막음 
=> 쿠키에 auth 존재 시 `home`  OR 쿠키에 auth 존재x `login` 으로 리다이렉트
+ 로그인 안되어있을 시(쿠키에 auth가 존재하지 않을 시)
`home`, `my`, `create`, `edit` 페이지 접근 => `login` 페이지로 리다이렉트
+ 로그인 되어있을 시(쿠키에 auth가 존재할 경우) 
`login` 페이지 접근 => `home`으로 리다이렉트
+ 시즌이 아닐 때, `create`, `edit` 페이지 접근 => `home`으로 리다이렉트
> 쿠키에 `auth`가 존재할 때(토큰이 존재할 때)도 로그인 만료되었을 수도 있지만, 이는 인터셉터에서 판단하는 게 좋을 것 같고, middleware에서는 지금처럼  **auth의 존재여부**, **시즌 여부**에 따라 바로 판단할 수 있는 로직만 넣었습니다. 추가하거나 삭제해야 할 리다이렉트 조건이나 로직이 있다면 말해주세요 !!

[민우] - 각 페이지 진입 및 완료 로직

---

src/apis/client/getAllPlans.ts
src/app/(headerless)/login/page.tsx

close #154 
- authorization: false로 변경했습니다. (타인 계획 페이지 API는 토큰이 필요 없음)

[혜수] - getAllPlans 토큰이 필요하지 않도록 수정

---

src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/home/_components/NewPlan/NewPlan.tsx

close #144 
- 이메일 인증여부에 따라 새 계획 생성 시 이메일 인증 모달 띄우기 추가

[혜수] - 이메일 인증여부에 따라 새 계획 생성시 이메일 인증 모달 띄우기 추가

---

src/app/(header)/explore/_components/ExplorePlans.tsx
src/app/(header)/explore/_components/Plans/Plans.tsx
src/components/Modal/index.scss

close #173
- 로그인 하지 않은 유저일 때 카드 컴포넌트 클릭 시 로그인 유도 모달 추가
- 모달 블러처리 화면 전체로 수정

[혜수] - 로그인 하지 않은 유저일 때 카드 컴포넌트 클릭 시 로그인 유도 모달 추가

---

src/app/(header)/explore/_components/Plans/Plans.tsx
src/components/AjajaButton/AjajaButton.tsx

close #170
- Plans 모달의 위치 map 밖으로 이동 -> 불필요한 반복 제거
- 아좌좌버튼 ajajaCount가 변경되었을 때 count도 함께 변경

[혜수] - 다른 계획 둘러보기 페이지에서 아좌좌 수 정상적으로 보이도록 변경

---

src/app/(header)/my/error.tsx
src/components/ModalVerification/ModalVerification.tsx
src/hooks/apis/useGetPlanQuery.ts
src/hooks/apis/useGetUserInformationQuery.ts
src/hooks/apis/useRefreshNicknameMutation.ts

close #184 
- useGetPlanquery ,useGetUSerInformationquery =>  useSuspense 교체
- 에러페이지 추가
- useRefreshNicknameMutaion => throwOnError: true 
- mutation 시 특정 에러 throw 처리   
바운더리에 전달되지 않는 문제는 useEffect로 해결했습니다.

[노철] - react query 에러핸들링

---

src/app/layout.tsx
src/components/Remind/WritableRemind/WritableRemind.tsx

[민우] - icon 오류 해결 및 리마인드 옵션 확정 버튼 로직 수정

---

src/app/(header)/my/page.tsx
src/constants/api.ts
src/types/apis/users/GetUserInformation.ts

close #204 
- 회원 탈퇴 후 로그아웃 진행 
- 유저정보 변수명 변경 ( 스웨거 기준)
- isEmailVerified=> emailVerified
이전에 있었던  회원탙퇴가 안되던 이슈는 
회원 탈퇴 api를 구현해 놓고 목으로 연결해서 안됐던 것 같습니다.

[노철] -  회원탈퇴 api

---

src/app/(header)/create/index.scss
src/app/(header)/create/page.tsx
src/app/(header)/edit/[planId]/index.scss
src/app/(header)/edit/[planId]/page.tsx
src/app/(header)/plans/[planId]/index.scss
src/app/(header)/plans/[planId]/page.tsx
src/components/Dropdown/index.scss
src/components/PlanInput/PlanInput.tsx
src/components/PlanInput/index.scss
src/components/Remind/ReadOnlyRemind/index.scss
src/components/Remind/WritableRemind/WritableRemind.tsx
src/components/Remind/WritableRemind/index.scss
src/components/RemindInput/RemindInput.tsx
src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
src/components/RemindItem/WritableRemindItem/index.scss
src/hooks/apis/useDeletePlanMutation.ts
src/hooks/apis/useEditPlanMutation.ts
src/hooks/apis/usePostNewPlanMutation.ts

[민우] - 작성, 수정, 상세 페이지 디자인 수정 및 에러 해결 및 토스트 적용

---

src/app/(header)/create/index.scss
src/app/(header)/edit/[planId]/index.scss
src/app/(header)/plans/[planId]/index.scss
src/components/Dropdown/index.scss
src/components/PlanInput/PlanInput.tsx
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/components/Remind/WritableRemind/WritableRemind.tsx
src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
src/components/RemindItem/ReadOnlyRemindItem/index.scss
src/components/RemindItem/WritableRemindItem/index.scss
src/components/WritablePlan/WritablePlan.tsx

[민우] - 디자인 수정

---

src/app/layout.tsx
src/components/Icon/Icon.tsx
src/styles/class/font-size.scss
src/types/IconName.ts

close #247 
``` ts
export type IconName =
| 'PLUS' // 내 계획 페이지 + 버튼
| 'CREATE_NEW_PLAN' // 계획 작성
| 'FEEDBACK' // 피드백
| 'OTHER_PLAN' // 다른 계획 둘러보기
| 'HOME' // 홈
| 'PROFILE' // 마이 페이지
| 'COPY'  // 링크 복사 아이콘
```

[민우] - Icon 컴포넌트 수정

---

src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/index.scss

close #247
https://github.com/New-Barams/this-year-ajaja-fe/assets/31370590/1f4c6e3a-4462-4f07-ae00-8bcd14d5e31a
현재 dropdown 내 옵션이 많아 스크롤 되는 경우는 리마인드 날짜(1일, 2일, 3일 ... 31일) 선택하는 경우인데, 이 경우 스크롤이 생기면 아래처럼 hover 효과나 가운데 정렬이 이쁘지 않아 지금처럼 scrollbar 안보이도록 처리해주었습니다 !

[민우] - Dropdown 컴포넌트 수정

---

src/app/(headerless)/login/index.scss
src/app/index.scss
src/app/layout.tsx
src/styles/origin-theme.scss
src/styles/standard.scss
src/styles/themes.scss

close #244 
- 외부 레이아웃 디자인 추가
- 반응형 구현
- 로그인 페이지만 적용해놨습니다.
기존 페이지에 width: 100% height:100%로 하면 적용 될 것 같습니다.
https://github.com/New-Barams/this-year-ajaja-fe/assets/67812466/77d1d659-b512-401b-a49e-194ff0404058

[혜수] - 외부 레이아웃 디자인 변경(위치만 잡아놓기) 

---

src/components/IconSwitchButton/IconSwitchButton.tsx
src/components/IconSwitchButton/index.scss
src/components/InputTag/InputTag.tsx
src/components/InputTag/index.scss
src/components/SwitchButton/index.scss
src/components/Tag/Tag.tsx
src/components/Tag/index.scss

close #246 
- Tag 컴포넌트 스타일 변경 및 props 변경
```tsx
interface TagProps extends React.HTMLAttributes<HTMLDivElement>{
children: React.ReactNode; // 태그 내용
classNameList?: string[];
}
<Tag >태그 내용</Tag>
<Tag onClick={handleOnClick}>태그내용</Tag>
```
- InputTag 컴포넌트 스타일 변경
```tsx
interface InputTagProps {
onSubmit: (submitValue: string) => void; //태그 생성을 위한 submit함수
}
<InputTag
onSubmit={(value: string) => {console.log(value)}}
/>
```
- SwitchButton 크기 고정 및 IconSwitchButton 아이콘 스타일 변경 
```tsx
interface IconSwitchButtonProps {
onIconName: OnIconName; // 우측에 위치할 아이콘이름
offIconName: OffIconName; //좌측에 위치할 아이콘이름
onClick: () => void; // 연결할 함수 
isActive: boolean; // 초기값, default = false
}
// 현재 아이콘은 NOTIFICATION, PLAN만 가능 
<IconSwitchButton
onIconName="NOTIFICATION_ON"
offIconName="NOTIFICATION_OFF" …
```

[노철] - 공용 컴포넌트 변경

---

src/components/PlanInput/PlanInput.tsx
src/components/PlanInput/index.scss
src/components/RemindInput/RemindInput.tsx
src/components/RemindInput/index.scss

close #252 
https://github.com/New-Barams/this-year-ajaja-fe/assets/31370590/209d0d4f-faae-4eb8-ab25-c05566b2a774
https://github.com/New-Barams/this-year-ajaja-fe/assets/31370590/7f9f4e98-8d5b-43c8-a9e3-0426b44ee462

[민우] - planInput, remindInput 컴포넌트 수정

---

src/app/index.scss
src/app/layout.tsx
src/components/AjajaButton/AjajaButton.tsx
src/components/AjajaButton/index.scss
src/components/Button/Button.tsx
src/components/Button/index.scss
src/styles/class/font-size.scss
src/styles/font.scss
src/styles/reset.scss
src/types/Color.ts

close #254 
- 화면 내부 마진 생성
- reset.scss button 추가
- font-size 기준 변경 & line-height 추가
- Color type 색상 추가
- 아좌좌 버튼 스타일 변경
- 버튼 컴포넌트 수정
-> 버튼 그림자 추가 완료
위치는 나중에 수정 예정입니다.
-> 프레임 그림자 추가 완료

[혜수] - 공통 컴포넌트 변경(아좌좌 버튼, 일반 버튼)

---

src/apis/axiosInstanceClient.ts
src/apis/client/postReissue.ts
src/app/(headerless)/oauth/hooks/useOauthPage.ts
src/constants/api.ts
src/types/apis/ErrorResponseData.ts
src/utils/checkTokenExp.ts
src/utils/decodeJWT.ts

close #251 
- accessToken 만료시 토큰 재발행 후 retry를 합니다. 
- accessToken, refreshToken 모두 만료시 다시 로그인 요청
- 로그인 실패시 에러 처리
만약 api 요청, 재발행 후 요청에서 문제가 있으면  알려주세요, 아직 모든 에러를 다 못 잡은 것 같습니다. 
- 재로그인시 유저에게  실패를 알려줄 때 , toast 보다 alert으로 확실하게 유저가 확인하도록 했습니다. 디자인 달라서 좀 별로인데 다른 방법이 있을까요? 아니면 toast를 alert과 같이 변경할수있을까요? 
- 현재 클라이언트 axiosInstance만 적용됐는데 서버쪽 axiosinstance를 어떻게 할지 잘 모르겠네용

[노철] - 토큰 갱신 로직 추가

---

src/app/(header)/explore/_components/Card/index.scss
src/app/(header)/explore/_components/ExplorePlans.tsx
src/app/(header)/explore/_components/Tab/index.scss
src/app/(header)/explore/_components/index.scss
src/app/(header)/home/_components/MyPlan.tsx
src/app/(header)/home/_components/index.scss
src/styles/standard.scss
src/styles/webkit.scss

close #284 
- explore, home 스크롤 적용 완료
- 스크롤 width 0.25rem으로 변경 완료
- 전역 --scroll-margin-left : 0.25rem 추가
- 스크롤 적용은 3d6bbbc 처럼 useScroll 훅을 사용해 스크롤이 생기는 태그에 ref와 onScroll 적용해주면 됩니다!
- 스크롤은 overlay 기능이 deprecated되어 사용할 수 없는 관계로 양옆 마진으로 해결했습니다 😢 
스크롤이 추가되는 태그에 아래의 css를 추가해주시면 됩니다. `overflow-y:scroll`로 하셔야합니다!(autoX)
```
overflow-y: scroll;
margin-left: var(--scroll-margin-left);
```

[혜수] - 스크롤 적용 위치 변경

---

src/apis/client/editRemind.ts
src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
src/app/(header)/create/page.tsx
src/app/(header)/reminds/[planId]/index.scss
src/app/(header)/reminds/[planId]/page.tsx
src/app/(header)/reminds/edit/[planId]/index.scss
src/app/(header)/reminds/edit/[planId]/page.tsx
src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
src/components/ModalFixRemindDate/index.scss
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/constants/api.ts
src/constants/createPlanSessionKey.ts
src/hooks/apis/useEditRemindMutation.ts
src/types/Remind.ts
src/types/apis/plan/EditRemind.ts
src/types/apis/plan/PostNewPlan.ts

[민우] - 리마인드 수정 페이지

---

src/app/(header)/create/page.tsx
src/app/(header)/reminds/edit/[planId]/page.tsx
src/components/CreatePlanContent/CreatePlanContent.tsx
src/components/CreatePlanContent/index.scss
src/components/CreatePlanIcon/CreatePlanIcon.tsx
src/components/CreatePlanIcon/index.scss
src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
src/components/CreatePlanRemindDate/index.scss
src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
src/components/CreatePlanRemindMessage/index.scss
src/components/DebounceSwitchButton/index.scss
src/components/ModalContinueCreate/ModalContinueCreate.tsx
src/components/ModalContinueCreate/index.scss
src/constants/createPlanSessionKey.ts
src/utils/getSessionStorageData.ts

[민우] - 작성 페이지 진입 로직 및 디자인 수정

---

src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
src/app/(header)/create/index.scss
src/app/(header)/create/page.tsx
src/app/(header)/reminds/[planId]/index.scss
src/app/(header)/reminds/[planId]/page.tsx
src/app/(header)/reminds/edit/[planId]/page.tsx
src/components/CreatePlanIcon/CreatePlanIcon.tsx
src/components/CreatePlanIcon/index.scss
src/components/CreatePlanIconExample/CreatePlanIconExample.tsx
src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
src/components/CreatePlanRemindMessage/index.scss
src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
src/constants/editRemindStepTitle.ts
src/types/Remind.ts

[민우] - 리마인드 정보 조회, 수정 API 연결

---

src/app/(headerless)/oauth/hooks/useOauthPage.ts

close #324 
- 쿠키저장 후 라우팅을 windwow.location.replace() 로 변경, 새로고침으로 바로 쿠키적용

[노철] - 쿠키 저장 및 라우팅 방식 변경

---

src/app/(header)/home/_components/MyPlan.tsx
src/app/_components/Navigation/Navigation.tsx
src/constants/plan.ts

close #330 
-  네비게이션바에 계획 생성 가능 여부 홈으로 가지 않아도 적용 될 수 있도록 수정
- 새로고침해도 유지 됩니다!

[혜수] - 네비게이션바에 계획 생성 가능 여부 전역상태관리 추가

---

src/app/_components/Navigation/Navigation.tsx

close #333 
- 리마인드, 계획 수정, 둘러보기 계획 조회(자신의 것인지 아닌지) nav에 적용 완료
- 리마인드는 홈에 표시
- 계획 수정은 계획 작성에 표시
- 계획 단건 조회는 자신의 것일 때 홈, 타인의 것일 때 둘러보기에 표시

[혜수] - 위치에 따라 nav bar 표시 변경

---

src/app/(header)/explore/_components/Card/Card.tsx
src/app/(header)/explore/_components/Card/index.scss
src/app/(header)/explore/_components/Tab/Tab.tsx
src/app/(header)/home/_components/NewPlan/NewPlan.tsx
src/app/(header)/home/_components/NewPlan/index.scss

close #365 
- 태그가 없을 때 태그가 없습니다 문구 제거
- 둘러보기 지난해 탭 임시 제거
- 카드 아이콘 여백 늘리기
- 홈 설문조사 링크 추가
홈 설문조사 마진 수정했습니다.

[혜수] - 둘러보기 페이지 UI 수정 & 홈 설문조사 링크 추가 

---

src/components/CreatePlanContent/CreatePlanContent.tsx

[민우] - 계획 작성 시 리마인드 알림 도움말 버튼 추가 

---

src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
src/hooks/apis/useToggleAjajaNotificationMutation.ts
src/hooks/apis/useToggleIsPublicMutation.ts

close #372 
-토글시 에러 핸들링 toast 로 변경

[노철] - 토글 에러 핸들링

---

src/apis/client/deletePlan.ts
src/apis/client/editPlan.ts
src/apis/client/postNewPlan.ts

[민우] - 배포 위한 변수 설정

---

src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
src/types/apis/plan/PostNewPlan.ts

[민우] - 계획 작성 API 호출 시 생략된 field 추가

---

src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
src/components/ModalFixRemindDate/index.scss

[민우] - 리마인드 날짜 확정 모달 디자인 변경

---

src/app/(header)/my/page.tsx
src/app/(header)/plans/edit/[planId]/page.tsx
src/components/ModalVerification/ModalVerification.tsx
src/components/ModalVerification/index.scss
src/components/PlanInput/PlanInput.tsx

close #390 
- 계획 상세에서 글자색 변경을 위해서 planInput component의 textarea 클래스에 직접 'color-origin-text-100'을 넣어줬습니다.  PlanInput 쓰는 곳을 다른 컴포넌트를 확인했는데 다 글자색이 검정색이라 괜찮을 것 같은데 , 혹시  문제가 될 수 있을까요?

[노철]- 수정, 마이페이지 

---

src/app/layout.tsx
src/components/ModalVerification/ModalVerification.tsx
src/hooks/apis/usePostSendVerificationMutation.ts
src/hooks/apis/usePostVerifyMutation.ts

close #402
- 이메일 인증 관련 에러를 useEffect로 하고 있었는데 적절하지 않아서 react-query의 throwOnError로 변경
- html lang ko 변경

[노철]- 이메일 인증 에러 핸들링 

---

src/app/(headerless)/notice/error.tsx
src/app/(headerless)/notice/index.scss
src/app/(headerless)/notice/page.tsx

close #416 
공지사항 페이지 dummy data로 임시로 구현해두었습니다.

[민우] - 공지사항 페이지 구현 

---

src/apis/client/postRemindTest.ts
src/components/ModalSendRemindExample/ModalSendRemindExample.tsx
src/constants/api.ts
src/hooks/apis/usePostRemindTest.ts

[민우] - 리마인드 예시 보내보기 API 연동 작업

---

src/app/(header)/explore/_components/Card/Card.tsx
src/app/(header)/explore/_components/Card/index.scss

close #421 
- 둘러보기 카드에서 올해 작성한 계획은 년도 제거하고 날짜 넣기
- 태그 2줄일 때 아래 공간 추가

[혜수] - 둘러보기 카드에서 올해 작성한 계획은 년도 제거하고 날짜 넣기

---

src/app/(header)/my/index.scss
src/app/(header)/my/page.tsx
src/components/ReadOnlyPlan/ReadOnlyPlan.tsx

close #430 
- 마이페이지 공지 사항  링크 추가
- 계획 상세  카카오 주의 사항 문구 제거

[노철] - 마이페이지 공지사항 추가
